// Curated genre list. Free-form text lookups for albums/artists/songs are great,
// but "genre" benefits from a normalized set so matching actually works.
// Easy to extend — just add to the list.

export const GENRES = [
  "Alt-country",
  "Alternative",
  "Ambient",
  "Americana",
  "Bluegrass",
  "Blues",
  "Bossa nova",
  "Breakbeat",
  "Britpop",
  "Cinematic",
  "Classical",
  "Country",
  "Dance",
  "Disco",
  "Dream pop",
  "Drum & bass",
  "Dub",
  "Electronic",
  "Emo",
  "Experimental",
  "Folk",
  "Funk",
  "Garage",
  "Grime",
  "Grunge",
  "Hardcore",
  "Hip-hop",
  "House",
  "Indie",
  "Indie folk",
  "Indie pop",
  "Indie rock",
  "Industrial",
  "Jazz",
  "Jungle",
  "K-pop",
  "Latin",
  "Lo-fi",
  "Math rock",
  "Metal",
  "Neo-soul",
  "New wave",
  "Noise",
  "Pop",
  "Post-punk",
  "Post-rock",
  "Progressive rock",
  "Psychedelic",
  "Punk",
  "R&B",
  "Reggae",
  "Reggaeton",
  "Rock",
  "Shoegaze",
  "Singer-songwriter",
  "Ska",
  "Soul",
  "Soundtrack",
  "Synth-pop",
  "Techno",
  "Trance",
  "Trap",
  "Trip-hop",
  "World",
];
